In [26]:
import os
import sys
import json
import ast
import time
import re
import configparser
from pathlib import Path
from typing import Any, List, Mapping, Optional, Iterator

# # Importation des bibliothèques liées à SQLite
# __import__("pysqlite3")
# sys.modules["sqlite3"] = sys.modules.pop("pysqlite3")

# Gestion des variables d'environnement
from dotenv import load_dotenv

load_dotenv()

# Définition des constantes pour les variables d'environnement
WATSONX_APIKEY = os.getenv("WATSONX_APIKEY", "")
WATSONX_PROJECT_ID = os.getenv("PROJECT_ID", "")
WATSONX_URL = os.getenv("WATSONX_URL", "https://us-south.ml.cloud.ibm.com/")

os.environ["WATSONX_URL"] = WATSONX_URL
os.environ["WATSONX_APIKEY"] = WATSONX_APIKEY
os.environ["WATSONX_PROJECT_ID"] = WATSONX_PROJECT_ID

# Importation des bibliothèques liées à IBM Watsonx
from ibm_watsonx_ai import Credentials
from ibm_watsonx_ai.foundation_models import Model
from ibm_watsonx_ai.metanames import (
    EmbedTextParamsMetaNames as EmbedParams,
    GenTextParamsMetaNames as GenParams,
)
from ibm_watsonx_ai.foundation_models.utils.enums import (
    EmbeddingTypes,
    ModelTypes,
    DecodingMethods,
)

credentials = Credentials(url=WATSONX_URL, api_key=WATSONX_APIKEY)

# # Bibliothèques liées à Streamlit
# import streamlit as st
# from streamlit_file_browser import st_file_browser

# Bibliothèques de traitement de données
import pandas as pd
import mdpd

# Bibliothèques de traitement de documents
import docling
from docling.backend.msword_backend import MsWordDocumentBackend
from docling.datamodel.base_models import InputFormat
from docling.datamodel.document import (
    ConversionResult,
    InputDocument,
    SectionHeaderItem,
)
from docling.document_converter import DocumentConverter

# Bibliothèques liées à Langchain et CrewAI
from crewai import Agent, Task, Crew, Process, LLM
from crewai.tools import tool
from langchain_community.tools import DuckDuckGoSearchRun
from langchain.agents import Tool, AgentType, AgentExecutor, create_react_agent
from langchain_experimental.tools.python.tool import PythonREPLTool
from langchain_core.runnables import chain
from langchain_core.document_loaders import BaseLoader
from langchain_core.documents import Document as LCDocument
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.document_loaders import Docx2txtLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain_ibm import WatsonxEmbeddings, WatsonxLLM, ChatWatsonx
from langchain_experimental.agents import create_pandas_dataframe_agent
from langchain_experimental.agents.agent_toolkits import create_csv_agent

# Bibliothèques liées à TM1py (IBM Planning Analytics)
from TM1py.Services import TM1Service
from TM1py.Utils.Utils import (
    build_pandas_dataframe_from_cellset,
    build_cellset_from_pandas_dataframe,
)


def get_credentials():
    return {
        "url": "https://us-south.ml.cloud.ibm.com",
        "apikey": os.getenv("WATSONX_APIKEY", ""),
    }


class DoclingPDFLoader(BaseLoader):
    def __init__(self, file_path: str | list[str]) -> None:
        self._file_paths = file_path if isinstance(file_path, list) else [file_path]
        self._converter = DocumentConverter()

    def lazy_load(self) -> Iterator[LCDocument]:
        for source in self._file_paths:
            dl_doc = self._converter.convert(source).document
            text = dl_doc.export_to_markdown()
            yield LCDocument(page_content=text)


def create_documents(path):
    loader = DoclingPDFLoader(file_path=path)
    file_name = loader._converter.convert(path).document.name
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200,
    )
    docs = loader.load()
    docs[0].metadata = {"filename": file_name}
    return text_splitter.split_documents(docs)


embed_params = {
    EmbedParams.TRUNCATE_INPUT_TOKENS: 512,
    EmbedParams.RETURN_OPTIONS: {"input_text": True},
}

embeddings = WatsonxEmbeddings(
    model_id="intfloat/multilingual-e5-large",
    url=os.getenv("WATSONX_URL", ""),
    apikey=os.getenv("WATSONX_APIKEY", ""),
    project_id=os.getenv("WATSONX_PROJECT_ID", ""),
    params=embed_params,
)


def create_vectorstore(path):
    texts = create_documents(path)
    return Chroma.from_documents(texts, embeddings)


doc_folder = "D:/Applications/Tm1/Tango_Core_Model/Data/Python_Scripts/PAAgenticAnalysis/agentic_analysis/Documents RAG"


def update_doc_folder(folder):
    folder_list_dir = os.listdir(folder)
    folder_list_dir = [f for f in folder_list_dir if f != ".gitignore"]
    return folder_list_dir


def add_documents(vectorbase, path):
    new_documents = create_documents(path)
    vectorbase.add_documents(new_documents)


docsearch = None
files_name = update_doc_folder(doc_folder)

document_dataframe = []

if files_name:
    file_path = os.path.join(doc_folder, files_name[0])
    docsearch = create_vectorstore(file_path)

for filename in files_name:
    if docsearch:
        if filename not in [
            doc["filename"] for doc in docsearch.get()["metadatas"] if doc
        ]:
            add_documents(docsearch, os.path.join(doc_folder, filename))

document_dataframe = list(
    set([doc["filename"] for doc in docsearch.get()["metadatas"] if doc])
)

pd.DataFrame({"Documents": document_dataframe}).to_csv("document_list.csv", index=False)

# to keep track of tasks performed by agents
task_values = []

config = configparser.ConfigParser()
config.read("config.ini")

WATSONX_LLAMA3_MODEL_ID = "watsonx/meta-llama/llama-3-2-3b-instruct"
model_id = "meta-llama/llama-3-2-3b-instruct"
model_id_mistral = "mistralai/mixtral-8x7b-instruct-v01"

parameters = {
    "decoding_method": "sample",
    "max_new_tokens": 3000,
    "temperature": 0.1,
    "top_k": 25,
    "top_p": 1,
    "repetition_penalty": 1,
}

parameters_llama = {
    "decoding_method": "sample",
    "max_new_tokens": 5000,
    "temperature": 0.5,
    "top_k": 25,
    "top_p": 1,
    "repetition_penalty": 1,
}

ibm_model = Model(
    model_id=model_id,
    params=parameters,
    credentials=credentials,
    project_id=WATSONX_PROJECT_ID,
)

pandas_llm = WatsonxLLM(
    model_id="meta-llama/llama-3-405b-instruct",  # codellama/codellama-34b-instruct-hf", #"mistralai/mistral-large", #"google/flan-t5-xxl", "ibm/granite-34b-code-instruct",
    url=get_credentials().get("url"),
    apikey=get_credentials().get("apikey"),
    project_id=WATSONX_PROJECT_ID,
    params=parameters,
)

# Create the function calling llm
function_calling_llm = WatsonxLLM(
    model_id="mistralai/mistral-large",
    url="https://us-south.ml.cloud.ibm.com",
    params=parameters,
    project_id=os.getenv("PROJECT_ID", ""),
)

llm = LLM(
    model="watsonx/meta-llama/llama-3-405b-instruct",
    base_url="https://api.watsonx.ai/v1",
    temperature=0.05,
    max_tokens=5000,
    # frequency_penalty=0.1,
    # presence_penalty=0.1,
    seed=42,
    top_p=0.8,
)


output_cube_name = "TM1py_output"
# définir et se connecter à l'instance tm1
with TM1Service(**config["tango_core_model"]) as tm1:

    def elements_aliase(dim_name, elem_list, alias_name):
        elem_aliases_dict = tm1.elements.get_attribute_of_elements(
            dimension_name=dim_name,
            hierarchy_name=dim_name,
            attribute=alias_name,
            elements=elem_list,
        )
        elem_aliases = list(elem_aliases_dict.values())
        return elem_aliases

    cube_name = tm1.cells.get_value(
        cube_name=output_cube_name,
        elements=[
            ("TM1py_Scripts", "AgenticAnalysis"),
            ("TM1py_outputs", "NomCube"),
        ],
    )
    view_name = tm1.cells.get_value(
        cube_name=output_cube_name,
        elements=[
            ("TM1py_Scripts", "AgenticAnalysis"),
            ("TM1py_outputs", "NomVue"),
        ],
    )
    # dimensions de la vue
    measure_dim = tm1.cubes.get_measure_dimension(cube_name=cube_name)
    country_dim = "Pays"
    period_dim = "Period"

    # vérification d'existence d'alias pour la dimension indicateur (autre que l'attribut format)
    measure_alias_names = tm1.elements.get_element_attribute_names(
        measure_dim, measure_dim
    )
    period_alias_names = tm1.elements.get_element_attribute_names(
        period_dim, period_dim
    )
    period_alias = tm1.elements.get_attribute_of_elements(
        period_dim, period_dim, "English"
    )
    countries = tm1.elements.get_leaf_element_names(
        dimension_name=country_dim, hierarchy_name=country_dim
    )  # liste de tous les pays feuilles de la dimension indicateurs

    all_indicators = tm1.elements.get_leaf_element_names(
        dimension_name=measure_dim, hierarchy_name=measure_dim
    )  # liste de tous les indicateurs feuilles de la dimension indicateurs

all_indicators_english = elements_aliase(
    "Indicateurs_Activité", all_indicators, "English"
)
countries_english = elements_aliase("Pays", countries, "English")

def round_2(number):
    """
    Converts str to float and round to the tenth
    """
    try:
        return round(float(number), 1)
    except:
        print("not a str")

def preprocessing(df, cube_name):
    """
    Preprocessing the dataframe
    """
    df = df.fillna(0)
    for col in df.columns[-12:]:
        df['Value'] = df['Value'].apply(round_2)
    # df = df.set_index(df.columns[0])
    for dim in tm1.cubes.get_dimension_names(cube_name=cube_name):
        if dim in df.columns:
            df[dim] = df[dim].apply(
                lambda x: tm1.elements.get_attribute_of_elements(
                    dimension_name=dim,
                    hierarchy_name=dim,
                    attribute="English",
                    elements=[x],
                )[x]
            )
    return df

def dimension_of_element(cube_name, view_name, element):
    cellset_sample = list(
        tm1.cubes.cells.execute_view(
            cube_name=cube_name, view_name=view_name
        ).keys()
    )[0]
    for dim in cellset_sample:
        if element in dim:
            first_bracket_index = dim.index("[")
            second_bracket_index = dim.index("]")
            return dim[first_bracket_index + 1 : second_bracket_index]

def get_context(cube_name, view_name):
    list_context = tm1.cubes.cells.execute_view_ui_dygraph(
        cube_name=cube_name, view_name=view_name, skip_zeros=False
    )["titles"][0]["name"]
    list_context = list_context.split(" / ")
    context = "For the following dataframe, the "
    for i, element in enumerate(list_context):
        elem_dim = dimension_of_element(cube_name, view_name, element)

        alias_name = tm1.elements.get_alias_element_attributes(
            dimension_name=elem_dim, hierarchy_name=elem_dim
        )[-1]
        try:
            elem_alias = list(
                tm1.elements.get_attribute_of_elements(
                    dimension_name=elem_dim,
                    hierarchy_name=elem_dim,
                    elements=[element],
                    attribute=alias_name,
                ).values()
            )[0]
        except:
            elem_alias = element
        context += f"{elem_dim} is {elem_alias}"
        if i < len(list_context) - 1:
            context += " and the "
    context = context.replace(measure_dim, "data displayed")
    return context

def view_dataframe(cube_name, view_name):
    return preprocessing(
        tm1.cubes.cells.execute_view_dataframe_shaped(
            cube_name=cube_name, view_name=view_name, skip_zeros=False
        ),
        cube_name,
    )

# current_dataframe = view_dataframe(cube_name, view_name)

# view_indicators_english = elements_aliase(
#     dim_name="Indicateurs_Activité",
#     elem_list=list(current_dataframe["Indicateurs_Activité"].unique()),
#     alias_name="English",
# )
# view_countries_english = elements_aliase(
#     dim_name="Pays",
#     elem_list=list(current_dataframe["Pays"].unique()),
#     alias_name="English",
# )

def dataframe_prompt_input(cube_name, view_name):
    dataframe = view_dataframe(cube_name, view_name)
    dataframe_md = dataframe.to_markdown()
    return dataframe_md

def dataframe_enriched_prompt_input(cube_name, view_name):
    context = f"""{get_context(cube_name,view_name)} \nDataframe:\n{dataframe_prompt_input(cube_name,view_name)}"""
    return context

d:\Applications\Tm1\Tango_Core_Model\Data\Python_Scripts\PAAgenticAnalysis\.venv\Lib\site-packages\ibm_watsonx_ai\foundation_models\model.py:101: DeprecationWarning: The `Model` class is deprecated and will be removed in a future release. Please use the `ModelInference` class instead. To update your imports, use: `from ibm_watsonx_ai.foundation_models import ModelInference`.
  warn(

In [30]:
output_cube_name = "TM1py_output"
# définir et se connecter à l'instance tm1
with TM1Service(**config["tango_core_model"]) as tm1:

    def elements_aliase(dim_name, elem_list, alias_name):
        elem_aliases_dict = tm1.elements.get_attribute_of_elements(
            dimension_name=dim_name,
            hierarchy_name=dim_name,
            attribute=alias_name,
            elements=elem_list,
        )
        elem_aliases = list(elem_aliases_dict.values())
        return elem_aliases

    cube_name = tm1.cells.get_value(
        cube_name=output_cube_name,
        elements=[
            ("TM1py_Scripts", "AgenticAnalysis"),
            ("TM1py_outputs", "NomCube"),
        ],
    )
    view_name = tm1.cells.get_value(
        cube_name=output_cube_name,
        elements=[
            ("TM1py_Scripts", "AgenticAnalysis"),
            ("TM1py_outputs", "NomVue"),
        ],
    )
    # dimensions de la vue
    measure_dim = tm1.cubes.get_measure_dimension(cube_name=cube_name)
    country_dim = "Pays"
    period_dim = "Period"

    # vérification d'existence d'alias pour la dimension indicateur (autre que l'attribut format)
    measure_alias_names = tm1.elements.get_element_attribute_names(
        measure_dim, measure_dim
    )
    period_alias_names = tm1.elements.get_element_attribute_names(
        period_dim, period_dim
    )
    period_alias = tm1.elements.get_attribute_of_elements(
        period_dim, period_dim, "English"
    )
    countries = tm1.elements.get_leaf_element_names(
        dimension_name=country_dim, hierarchy_name=country_dim
    )  # liste de tous les pays feuilles de la dimension indicateurs

    all_indicators = tm1.elements.get_leaf_element_names(
        dimension_name=measure_dim, hierarchy_name=measure_dim
    )  # liste de tous les indicateurs feuilles de la dimension indicateurs

all_indicators_english = elements_aliase(
    "Indicateurs_Activité", all_indicators, "English"
)
countries_english = elements_aliase("Pays", countries, "English")

def round_2(number):
    """
    Converts str to float and round to the tenth
    """
    try:
        return round(float(number), 1)
    except:
        print("not a str")

def preprocessing(df, cube_name):
    """
    Preprocessing the dataframe
    """
    df = df.fillna(0)
    for col in df.columns[-12:]:
        df['Value'] = df['Value'].apply(round_2)
    # df = df.set_index(df.columns[0])
    for dim in tm1.cubes.get_dimension_names(cube_name=cube_name):
        if dim in df.columns:
            df[dim] = df[dim].apply(
                lambda x: tm1.elements.get_attribute_of_elements(
                    dimension_name=dim,
                    hierarchy_name=dim,
                    attribute="English",
                    elements=[x],
                )[x]
            )
    return df

def dimension_of_element(cube_name, view_name, element):
    cellset_sample = list(
        tm1.cubes.cells.execute_view(
            cube_name=cube_name, view_name=view_name
        ).keys()
    )[0]
    for dim in cellset_sample:
        if element in dim:
            first_bracket_index = dim.index("[")
            second_bracket_index = dim.index("]")
            return dim[first_bracket_index + 1 : second_bracket_index]

def get_context(cube_name, view_name):
    list_context = tm1.cubes.cells.execute_view_ui_dygraph(
        cube_name=cube_name, view_name=view_name, skip_zeros=False
    )["titles"][0]["name"]
    list_context = list_context.split(" / ")
    context = "For the following dataframe, the "
    for i, element in enumerate(list_context):
        elem_dim = dimension_of_element(cube_name, view_name, element)

        alias_name = tm1.elements.get_alias_element_attributes(
            dimension_name=elem_dim, hierarchy_name=elem_dim
        )[-1]
        try:
            elem_alias = list(
                tm1.elements.get_attribute_of_elements(
                    dimension_name=elem_dim,
                    hierarchy_name=elem_dim,
                    elements=[element],
                    attribute=alias_name,
                ).values()
            )[0]
        except:
            elem_alias = element
        context += f"{elem_dim} is {elem_alias}"
        if i < len(list_context) - 1:
            context += " and the "
    context = context.replace(measure_dim, "data displayed")
    return context

def view_dataframe(cube_name, view_name):
    return preprocessing(
        tm1.cubes.cells.execute_view_dataframe_shaped(
            cube_name=cube_name, view_name=view_name, skip_zeros=False
        ),
        cube_name,
    )

In [38]:
df = tm1.cells.execute_view_dataframe(cube_name,view_name)

def round_value(df):
    df['Value'] = df['Value'].apply(round_2)

def to_english(cube_name,view_name):
    for dim in tm1.cubes.get_dimension_names(cube_name=cube_name):
        if dim in df.columns and dim != 'Period':
            df[dim] = df[dim].apply(
                lambda x: tm1.elements.get_attribute_of_elements(
                    dimension_name=dim,
                    hierarchy_name=dim,
                    attribute="English",
                    elements=[x],
                )[x])
    return df

def preprocessing_melt_english(df, cube_name,view_name):
    round_value(df)
    to_english(cube_name,view_name)
    return df

In [50]:
df.groupby(['Indicateurs_Activité', 'Pays', 'Period'])['Value'].agg(['min', 'max', 'sum']).groupby(['Indicateurs_Activité', 'Pays']).agg(['min', 'max', 'sum']).reset_index()

   Indicateurs_Activité      Pays    min                     max          \
                                     min     max      sum    min     max
0      Commercial Costs   Belgium   71.2  1281.0   6773.4   71.2  1281.0
1      Commercial Costs   Finland   78.4  1364.8   9121.2   78.4  1364.8
2      Commercial Costs  Portugal   75.6  1288.2   6842.2   75.6  1288.2
3      Commercial Costs    Sweden   87.4  1329.6   9025.7   87.4  1329.6
4         General Costs   Belgium  201.0  1091.2   9072.6  201.0  1091.2
5         General Costs   Finland  117.4  1106.4   8050.6  117.4  1106.4
6         General Costs  Portugal  210.6  1098.2   8880.2  210.6  1098.2
7         General Costs    Sweden  125.0  1081.8   7931.8  125.0  1081.8
8       Logistics Costs   Belgium  247.5  1281.0   8585.2  247.5  1281.0
9       Logistics Costs   Finland  236.4  1405.0   9161.5  236.4  1405.0
10      Logistics Costs  Portugal  298.6  1370.2   8975.0  298.6  1370.2
11      Logistics Costs    Sweden  248.6  1362.8   8985.9  248.6  1362.8
12      Marketing Costs   Belgium  321.0  1330.8  10923.8  321.0  1330.8
13      Marketing Costs   Finland  208.6  1248.2   9239.9  208.6  1248.2
14      Marketing Costs  Portugal  328.6  1332.4  10991.8  328.6  1332.4
15      Marketing Costs    Sweden  219.6  1226.4   9215.0  219.6  1226.4
16        Storage Costs   Belgium   61.0  1391.2   8703.0   61.0  1391.2
17        Storage Costs   Finland   76.8  1237.8   6023.3   76.8  1237.8
18        Storage Costs  Portugal   63.6  1396.2   8776.8   63.6  1396.2
19        Storage Costs    Sweden   85.8  1203.6   5968.7   85.8  1203.6

               sum
        sum    min     max      sum
0    6773.4   71.2  1281.0   6773.4
1    9121.2   78.4  1364.8   9121.2
2    6842.2   75.6  1288.2   6842.2
3    9025.7   87.4  1329.6   9025.7
4    9072.6  201.0  1091.2   9072.6
5    8050.6  117.4  1106.4   8050.6
6    8880.2  210.6  1098.2   8880.2
7    7931.8  125.0  1081.8   7931.8
8    8585.2  247.5  1281.0   8585.2
9    9161.5  236.4  1405.0   9161.5
10   8975.0  298.6  1370.2   8975.0
11   8985.9  248.6  1362.8   8985.9
12  10923.8  321.0  1330.8  10923.8
13   9239.9  208.6  1248.2   9239.9
14  10991.8  328.6  1332.4  10991.8
15   9215.0  219.6  1226.4   9215.0
16   8703.0   61.0  1391.2   8703.0
17   6023.3   76.8  1237.8   6023.3
18   8776.8   63.6  1396.2   8776.8
19   5968.7   85.8  1203.6   5968.7

In [128]:
df

        Pays Indicateurs_Activité   Period   Value
0    Finland     Commercial Costs  2025.01  1276.4
1    Finland     Commercial Costs  2025.02   122.5
2    Finland     Commercial Costs  2025.03  1108.5
3    Finland     Commercial Costs  2025.04  1038.4
4    Finland     Commercial Costs  2025.05   245.2
..       ...                  ...      ...     ...
235  Belgium      Marketing Costs  2025.08  1011.2
236  Belgium      Marketing Costs  2025.09  1120.8
237  Belgium      Marketing Costs  2025.10   321.0
238  Belgium      Marketing Costs  2025.11  1330.8
239  Belgium      Marketing Costs  2025.12  1161.2

[240 rows x 4 columns]

In [ ]:
df.groupby(['Pays','Indicateurs_Activité']).sum()

                                                                          Period  \
Pays     Indicateurs_Activité
Belgium  Commercial Costs      2025.012025.022025.032025.042025.052025.062025...
         General Costs         2025.012025.022025.032025.042025.052025.062025...
         Logistics Costs       2025.012025.022025.032025.042025.052025.062025...
         Marketing Costs       2025.012025.022025.032025.042025.052025.062025...
         Storage Costs         2025.012025.022025.032025.042025.052025.062025...
Finland  Commercial Costs      2025.012025.022025.032025.042025.052025.062025...
         General Costs         2025.012025.022025.032025.042025.052025.062025...
         Logistics Costs       2025.012025.022025.032025.042025.052025.062025...
         Marketing Costs       2025.012025.022025.032025.042025.052025.062025...
         Storage Costs         2025.012025.022025.032025.042025.052025.062025...
Portugal Commercial Costs      2025.012025.022025.032025.042025.052025.062025...
         General Costs         2025.012025.022025.032025.042025.052025.062025...
         Logistics Costs       2025.012025.022025.032025.042025.052025.062025...
         Marketing Costs       2025.012025.022025.032025.042025.052025.062025...
         Storage Costs         2025.012025.022025.032025.042025.052025.062025...
Sweden   Commercial Costs      2025.012025.022025.032025.042025.052025.062025...
         General Costs         2025.012025.022025.032025.042025.052025.062025...
         Logistics Costs       2025.012025.022025.032025.042025.052025.062025...
         Marketing Costs       2025.012025.022025.032025.042025.052025.062025...
         Storage Costs         2025.012025.022025.032025.042025.052025.062025...

                                 Value
Pays     Indicateurs_Activité
Belgium  Commercial Costs       6773.4
         General Costs          9072.6
         Logistics Costs        8585.2
         Marketing Costs       10923.8
         Storage Costs          8703.0
Finland  Commercial Costs       9121.2
         General Costs          8050.6
         Logistics Costs        9161.5
         Marketing Costs        9239.9
         Storage Costs          6023.3
Portugal Commercial Costs       6842.2
         General Costs          8880.2
         Logistics Costs        8975.0
         Marketing Costs       10991.8
         Storage Costs          8776.8
Sweden   Commercial Costs       9025.7
         General Costs          7931.8
         Logistics Costs        8985.9
         Marketing Costs        9215.0
         Storage Costs          5968.7

In [98]:
class DoclingPDFLoader(BaseLoader):
    def __init__(self, file_path: str | list[str]) -> None:
        self._file_paths = file_path if isinstance(file_path, list) else [file_path]
        self._converter = DocumentConverter()

    def lazy_load(self) -> Iterator[LCDocument]:
        for source in self._file_paths:
            dl_doc = self._converter.convert(source).document
            text = dl_doc.export_to_markdown()
            yield LCDocument(page_content=text)


def create_documents(path):
    loader = DoclingPDFLoader(file_path=path)
    file_name = loader._converter.convert(path).document.name
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=200,
        chunk_overlap=20,
    )
    docs = loader.load()
    docs[0].metadata = {"filename": file_name}
    return text_splitter.split_documents(docs)


embed_params = {
    EmbedParams.TRUNCATE_INPUT_TOKENS: 512,
    EmbedParams.RETURN_OPTIONS: {"input_text": True},
}

embeddings = WatsonxEmbeddings(
    model_id="intfloat/multilingual-e5-large",
    url=os.getenv("WATSONX_URL", ""),
    apikey=os.getenv("WATSONX_APIKEY", ""),
    project_id=os.getenv("WATSONX_PROJECT_ID", ""),
    params=embed_params,
)


def create_vectorstore(path):
    texts = create_documents(path)
    return Chroma.from_documents(texts, embeddings)


doc_folder = "D:/Applications/Tm1/Tango_Core_Model/Data/Python_Scripts/PAAgenticAnalysis/agentic_analysis/Documents RAG"


def update_doc_folder(folder):
    folder_list_dir = os.listdir(folder)
    folder_list_dir = [f for f in folder_list_dir if f != ".gitignore"]
    return folder_list_dir


def add_documents(vectorbase, path):
    new_documents = create_documents(path)
    vectorbase.add_documents(new_documents)


docsearch = None
files_name = update_doc_folder(doc_folder)

document_dataframe = []

if files_name:
    file_path = os.path.join(doc_folder, files_name[0])
    docsearch = create_vectorstore(file_path)

for filename in files_name:
    if docsearch:
        if filename not in [
            doc["filename"] for doc in docsearch.get()["metadatas"] if doc
        ]:
            add_documents(docsearch, os.path.join(doc_folder, filename))

document_dataframe = list(
    set([doc["filename"] for doc in docsearch.get()["metadatas"] if doc])
)

pd.DataFrame({"Documents": document_dataframe}).to_csv("document_list.csv", index=False)

In [109]:
query = 'Finland Passenger Revenues'
docs, scores = zip(
                *docsearch.similarity_search_with_relevance_scores(
                    query, score_threshold=0.67,
                )
            )
for doc, score in zip(docs, scores):
    doc.metadata["score"] = score

# gather all retrieved documents into single string paragraph
removed_n = [
    doc.page_content.replace("\n", " ") for doc in docs
]  # remove \n
unique_retrieval = list(set(removed_n))  # remove duplicates documents
retrieved_context = "\n".join(unique_retrieval)

In [110]:
print(retrieved_context)

Southern Europe: Spain &amp; Portugal  Spain  - Sales/Revenues:     - Passenger Revenues:
Scandinavia: Finland &amp; Sweden  Finland  - Sales/Revenues:     - Fuel Sales:  Goal 2025: €14,200k via Q2-Q3 promotions and EV charging partnerships.  - Passenger Revenues:
Germany  - Sales/Revenues:     - Passenger Revenues:

In [113]:
from ibm_watsonx_ai.foundation_models import ModelInference

rag_model_id = "mistralai/mistral-large"

# Defining the model parameters

rag_model_parameters = {
    "decoding_method": "greedy",
    "max_new_tokens": 6000,
    "min_new_tokens": 1,
    # "stop_sequences": ["\n\n"],
    "repetition_penalty": 1,
}

## Defining the Model object

rag_model = ModelInference(
    model_id=rag_model_id,
    params=rag_model_parameters,
    credentials=get_credentials(),
    project_id=WATSONX_PROJECT_ID,
)

prompt_input = f'Based on the CONTEXT, What is the target for Fuel Sales in Finland ? CONTEXT: {retrieved_context}'
rag_response = rag_model.generate_text(
    prompt=prompt_input, guardrails=False
)

In [112]:
prompt_input

'Based on the CONTEXT, What is the target for Fuel Sales in Finland ? CONTEXT: Southern Europe: Spain &amp; Portugal  Spain  - Sales/Revenues:     - Passenger Revenues:\nScandinavia: Finland &amp; Sweden  Finland  - Sales/Revenues:     - Fuel Sales:  Goal 2025: €14,200k via Q2-Q3 promotions and EV charging partnerships.  - Passenger Revenues:\nGermany  - Sales/Revenues:     - Passenger Revenues:'

In [114]:
rag_response

'\n\nThe target for Fuel Sales in Finland is €14,200k by 2025, to be achieved via Q2-Q3 promotions and EV charging partnerships.'

In [124]:
tm1.cells.execute_view_values(cube_name,view_name,)

[1343.6,
 129,
 1166.8,
 1038.4,
 245.2,
 619.6,
 1358.4,
 417.8,
 1364.8,
 963.8,
 527.4,
 78.4,
 514.2,
 848.4,
 947.8,
 229.4,
 1106.4,
 933.6,
 122.6,
 1044.8,
 979.4,
 362.8,
 117.4,
 843.8,
 1315.56,
 991.0400000000001,
 670.32,
 611.6099999999999,
 1334.75,
 225.53,
 325.47,
 349.41,
 224.58,
 1328.86,
 710.7900000000001,
 764.37,
 1237.8,
 182.6,
 847,
 458.4,
 167.4,
 243,
 76.8,
 1196.6,
 306.4,
 177.8,
 1346.8,
 109.6,
 527,
 219.6,
 369.4,
 626.4,
 1248.2,
 1063.4,
 637.8,
 1025.2,
 802.6,
 1034.4,
 797,
 944.8,
 1246.21,
 132.43,
 1081.86,
 1014.2,
 258.8,
 636.6,
 1326.8,
 429.2,
 1329.6,
 938.4,
 544.2,
 87.4,
 528.4,
 825.8,
 919.6,
 240.6,
 1081.8,
 907.4,
 134.2,
 1016.8,
 952.2,
 378.4,
 125,
 821.6,
 1347,
 1018.6,
 682.4,
 590.52,
 1294.6599999999999,
 238.64,
 337.06,
 366.32000000000005,
 236.17,
 1291.24,
 688.75,
 742.3299999999999,
 1203.6,
 188.4,
 829.4,
 472.2,
 176.2,
 252.8,
 85.8,
 1158.4,
 317.4,
 182.6,
 1308.2,
 114.8,
 550.6,
 231.2,
 383,
 616.8,
 1226.4,
 1042.8,
 649.8,
 997.4,
 824.2,
 1004.6,
 819.4,
 927,
 426.17,
 414.58,
 1223.79,
 75.6,
 1014.2,
 930.4,
 268.47,
 338.58,
 346.37,
 1034.2,
 374.4,
 236.6,
 748.6,
 1028.4,
 722.6,
 678.4,
 1010.2,
 1020.4,
 406.2,
 922.4,
 456.6,
 848.4,
 210.6,
 1098.2,
 1063.314,
 857.8679999999999,
 1245.674,
 543.782,
 562.9879999999999,
 557.3620000000001,
 396.14799999999997,
 1329.094,
 289.642,
 867.568,
 654.3620000000001,
 337.948,
 63.6,
 408.4,
 674.6,
 131.4,
 1368.4,
 1176.2,
 430.6,
 776.4,
 1396.2,
 1036.4,
 268.4,
 1046.2,
 1018.4,
 522.6,
 1382.4,
 878.2,
 398.4,
 1320.2,
 1224.6,
 1020.4,
 1126.2,
 328.6,
 1332.4,
 1170.2,
 441,
 431.2,
 1281,
 71.2,
 1001.2,
 921,
 281,
 351.2,
 361,
 1031.2,
 371.2,
 231.2,
 741,
 1020.8,
 721,
 671.2,
 1001,
 1011.2,
 401,
 921,
 451.2,
 841,
 201,
 1091.2,
 1091.2,
 881,
 1281,
 551.2,
 571.2,
 561,
 401,
 1361,
 291.2,
 891.2,
 671.2,
 341,
 61,
 401,
 671.2,
 121,
 1361,
 1171.2,
 421,
 771.2,
 1391.2,
 1031.2,
 261,
 1041,
 1011.2,
 520.8,
 1380.6,
 871.2,
 391.2,
 1311.2,
 1220.8,
 1011.2,
 1120.8,
 321,
 1330.8,
 1161.2]

In [189]:
df = tm1.cells.execute_view_dataframe(cube_name,view_name)

In [135]:
mdx = tm1.views.get_mdx_view(cube_name,view_name).MDX

In [139]:
mdx = mdx.replace("mois","year")

In [140]:
mdx

'SELECT {TM1SubsetToSet([Period].[Period],"2025_year","public")} ON 0, {EXCEPT(EXCEPT([Pays].[Pays].LEVELS(0).MEMBERS , {[Pays].[Pays].[Pays-Bas],[Pays].[Pays].[Royaume-Uni],[Pays].[Pays].[Irlande],[Pays].[Pays].[Allemagne],[Pays].[Pays].[République tchèque],[Pays].[Pays].[Slovaquie]}) , {[Pays].[Pays].[Espagne]})}*{[Indicateurs_Activité].[Indicateurs_Activité].[Coûts Commerciaux],[Indicateurs_Activité].[Indicateurs_Activité].[Coûts généraux],[Indicateurs_Activité].[Indicateurs_Activité].[Coûts Logistiques],[Indicateurs_Activité].[Indicateurs_Activité].[Coûts Stockage],[Indicateurs_Activité].[Indicateurs_Activité].[Coûts Marketing]} ON 1 FROM [00.Ventes] WHERE ([Phase].[Phase].[ACT_BUDG_NB^BUDG_ALL^BUDG_AJUST])'

In [142]:
df = tm1.cells.execute_mdx_dataframe(mdx=mdx)

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Pays                  20 non-null     object
 1   Indicateurs_Activité  20 non-null     object
 2   Period                20 non-null     object
 3   Value                 20 non-null     float64
dtypes: float64(1), object(3)
memory usage: 772.0+ bytes

In [156]:
df

         Pays Indicateurs_Activité   Period   Value
0    Finlande    Coûts Commerciaux  2025.01  1343.6
1    Finlande    Coûts Commerciaux  2025.02   129.0
2    Finlande    Coûts Commerciaux  2025.03  1166.8
3    Finlande    Coûts Commerciaux  2025.04  1038.4
4    Finlande    Coûts Commerciaux  2025.05   245.2
..        ...                  ...      ...     ...
235  Belgique      Coûts Marketing  2025.08  1011.2
236  Belgique      Coûts Marketing  2025.09  1120.8
237  Belgique      Coûts Marketing  2025.10   321.0
238  Belgique      Coûts Marketing  2025.11  1330.8
239  Belgique      Coûts Marketing  2025.12  1161.2

[240 rows x 4 columns]

In [172]:
import datetime

# df['Year'] = df['Period'].dt.strftime('%Y')
df['Year'] = pd.to_datetime(df['Period']).dt.strftime('%Y')

C:\Windows\Temp\ipykernel_58056\4138917478.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Year'] = pd.to_datetime(df['Period']).dt.strftime('%Y')

In [187]:
from datetime import datetime
period='2025.01'
datetime.strptime(period,'%Y.%M').date().strftime('%Y')

'2025'

In [196]:
df.groupby([df['Period'].str[:4],'Pays','Indicateurs_Activité'])['Value'].agg([min,max,sum])

                                        min     max      sum
Period Pays     Indicateurs_Activité
2025   Belgique Coûts Commerciaux      71.2  1281.0   6773.4
                Coûts Logistiques     291.2  1361.0   8893.2
                Coûts Marketing       321.0  1380.6  11652.0
                Coûts Stockage         61.0  1391.2   8703.0
                Coûts généraux        201.0  1091.2   9072.6
       Finlande Coûts Commerciaux      78.4  1364.8   9253.2
                Coûts Logistiques     236.4  1405.0   9318.2
                Coûts Marketing       219.6  1248.2   9295.8
                Coûts Stockage         76.8  1346.8   6350.2
                Coûts généraux        117.4  1106.4   8050.6
       Portugal Coûts Commerciaux      75.6  1288.2   6842.2
                Coûts Logistiques     298.6  1370.2   8975.0
                Coûts Marketing       328.6  1382.4  11722.6
                Coûts Stockage         63.6  1396.2   8776.8
                Coûts généraux        210.6  1098.2   9151.0
       Suède    Coûts Commerciaux      87.4  1329.6   9155.2
                Coûts Logistiques     248.6  1362.8   9138.2
                Coûts Marketing       231.2  1226.4   9273.2
                Coûts Stockage         85.8  1308.2   6289.8
                Coûts généraux        125.0  1081.8   7931.8

In [198]:
ast.literal_eval("{'indicator':'Logistics Costs','percent':'-1.5','country':'Finland','month':'September'}")

{'indicator': 'Logistics Costs',
 'percent': '-1.5',
 'country': 'Finland',
 'month': 'September'}

In [200]:
float('-1.5')/100

-0.015

In [207]:
def check_if_numeric(cur_string):
    symbols = ["-", "+", ",", "."]
    for symbol in symbols:
        cur_string = cur_string.replace(symbol, "")
    return cur_string.isnumeric()

In [208]:
check_if_numeric('-1.5')

True

In [275]:
tm1.cells.write(cube_name=cube_name,
                            cellset_as_dict={
                                ("BUDG_VC_AJUST%",
                                '2025.07',
                                'Finland',
                                'Logistics Costs'):-0.000015
                            },precision=4)

In [264]:
round(0.015,2)

0.01